import type { Metadata } from "next";
import { satoshi, generalSans } from "./fonts";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Footer from "@/components/footer";
import { SimpleNavbar } from "@/components/simple-navbar";
import { WalletProvider } from "@/hooks/use-wallet";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSans.variable} ${satoshi.variable} antialiased`}>
        <WalletProvider>
        {/* Sidebar + Main in one row */}
       <SimpleNavbar />
        <div className="flex min-h-screen gap-5">
          <Sidebar />
          
          <div className="flex-1  text-white overflow-y-auto">
            {children}
          </div>
        </div>

        {/* Footer independent at bottom */}
        <Footer />
        </WalletProvider>
      </body>
    </html>
  );
}
